# Generated by Django 5.2.4 on 2025-07-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
