# Generated by Django 5.2.4 on 2025-07-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_summary_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='due_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
