# Generated by Django 5.2.4 on 2025-07-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_minutes', models.PositiveIntegerField(default=60, help_text='Maximum minutes of audio per month')),
                ('used_minutes', models.PositiveIntegerField(default=0, help_text='Used minutes of audio this month')),
                ('reset_date', models.DateField(auto_now_add=True, help_text='Date when the quota resets')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the quota was created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
