# Generated by Django 5.2.4 on 2025-07-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the audio file', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the audio file', max_length=255)),
                ('size', models.PositiveIntegerField(help_text='Size of the audio file in bytes')),
                ('extention', models.CharField(help_text='File extension (e.g., mp3, wav)', max_length=10)),
                ('durtion_seconds', models.PositiveIntegerField(help_text='Duration of the audio file in seconds')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio File',
                'verbose_name_plural': 'Audio Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
