# Generated by Django 5.2.4 on 2025-07-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='extention',
            new_name='extension',
        ),
    ]
